[tool.poetry]
name = "satispaython"
version = "0.2.4"
description = "A simple library to manage Satispay payments following the Web-button flow."
license = "GPL-3.0-or-later"
authors = ["Daniele Pira <daniele.pira@otto.to.it>"]
readme = "README.md"
repository = "https://github.com/otto-torino/satispaython"
keywords = ["python", "satispay"]
classifiers = ["Topic :: Software Development :: Libraries :: Python Modules"]

[tool.poetry.dependencies]
python = "^3.6"
requests = "^2.23"
cryptography = "^3.3"

[tool.poetry.dev-dependencies]
responses = "^0.12"
pytest-cov = "^2.10"
pytest-freezegun = "^0.4.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
